spring:
  application.name: adventure-book
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    name: adventure-book-ds
    tomcat:
      jmx-enabled: true
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      connection-test-query: SELECT 1
      validation-timeout: 15000
      connection-timeout: 30000
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true
        format_sql: false
        use_sql_comments: false
        batch_size: 100
        order_inserts: true
        order_updates: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: adventure_book