name: Post Merge

run-name: ${{ github.ref_name }}-${{ github.run_number }} ${{ github.workflow }}

# triggers when a pull-request is merged to the develop branch
on:
  pull_request_target: # pull-request merged
    branches:
      - 'develop'
      - 'main'
    types:
      - 'closed'

env:
  APP_NAME: adventure-book

jobs:
  post-merge:
    if: ${{ (github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    steps:
      - name: Checkout the source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Maven Build
        run: mvn clean install -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Docker Build and Push
        run: |
          echo "Building Img Name: ${image_name_r} with tag: ${image_tag_r}"
          docker build . -t ${image_name_r}:${image_tag_r}
          docker image tag ${image_name_r}:${image_tag_r} ${image_name_r}:latest
#          docker image push --all-tags ${image_name_r}
        env:
          image_name_r: "${{env.APP_NAME}}"
          image_tag_r: ${{ steps.get_version.outputs.version }}